name: mensa_italia_app
description: A new Flutter project.
publish_to: "none"
version: 21.14.42+211442

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: "3.4.4"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.2.0
  enefty_icons: ^1.0.7
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_flip_card: ^0.0.6
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.1.0
  gyro_provider: ^0.1.0
  html: ^0.15.6
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.3.0
  modal_bottom_sheet: ^3.0.0
  native_dio_adapter: ^1.4.0
  path_provider: ^2.1.5
  pocketbase: ^0.23.0+1
  shared_preferences: ^2.5.3
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  stylish_bottom_bar: ^1.1.1
  super_cupertino_navigation_bar: ^2.1.2
  url_launcher: ^6.3.1
  form_validator: ^2.1.1
  webview_flutter: ^4.12.0
  intl: any
  dart_rss: ^3.0.3
  image_picker: ^1.1.2
  dotted_border: ^3.1.0
  maplibre_gl: ^0.22.0
  package_info_plus: ^8.2.1
  syncfusion_flutter_pdfviewer: ^31.2.12
  flutter_localizations:
    sdk: flutter
  webview_cookie_manager_plus: ^2.0.16
  open_filex: ^4.7.0
  table_calendar: ^3.1.3
  geocoding: ^4.0.0
  geolocator: ^13.0.3
  latlong2: ^0.9.1
  fluttertoast: ^9.0.0
  maps_launcher: ^3.0.0+1
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  device_info_plus: ^12.2.0
  omni_datetime_picker: ^2.1.1
  app_version_update: ^6.1.3
  easy_localization: ^3.0.7
  mobile_scanner: ^7.0.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  link_text: ^0.2.1
  flutter_linkify: ^6.0.0
  expandable_widgets: ^1.0.3+1
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_stripe: ^12.1.1
  carousel_slider: ^5.0.0
  gpt_markdown: ^1.0.19
  badges: ^3.1.2
  place_picker_google: ^0.0.16
  shimmer: ^3.0.0
  app_links: ^6.4.0
  share_plus: ^12.0.1
  objectbox: any
  objectbox_flutter_libs: any
  google_api_headers: ^4.5.8
  pretty_qr_code: ^3.5.0
  flutter_wallet_card: ^4.0.4
  pulsing_border: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.1
  stacked_generator: ^2.0.0
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.3
  objectbox_generator: any

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#234190"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/cards/

  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/Gotham-Book.otf
        - asset: fonts/Gotham-Bold.otf
          weight: 700
        - asset: fonts/Gotham-Light.otf
          weight: 300
        - asset: fonts/Gotham-Medium.otf
          weight: 500
        - asset: fonts/Gotham-Thin.otf
          weight: 100
